# List of valid properties:
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# [global]
command=~/.i3/i3blocks/blocks/$BLOCK_NAME
separator_block_width=15
markup=none
signal=10

[bandwidth]
instance=enp2s0;in
label=
interval=1

[bandwidth]
instance=enp2s0;out
label=
interval=1

[cpu]
label=
interval=2

#[audio]
#label=
#interval=once

#TODO: fix showing when no battery
[battery]
label=
instance=0
interval=30

[memory]
label=
instance=mem;free
interval=30

[space]
label=
interval=30

[ssid]
label=
interval=10

#[iface]
#label=
#color=#00FF00
#interval=10
#separator=false

#[wifi]
#interval=10
#separator=false

[packages]
label=
interval=300

[locale]
label=
interval=once

[weather]
instance=456172
interval=60

[time]
label=
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
